name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_VERSION: 3.1.101
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal --configuration Release

      - name: Create NuGet package
        run: dotnet pack --configuration Release --no-build --output ./nupkg
#      - name: Publish Nuget
#        run: dotnet nuget push ./Fynance/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --skip-duplicate --source "https://api.nuget.org/v3/index.json"
